name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'token for the API'
    required: true

# Define your outputs here.
outputs:
  pull_request_number:
    description: 'Pull request number'

runs:
  using: node20
  main: dist/index.js
